adjusted host in DB settings to IP and added test for SSH key in deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -50,6 +50,12 @@ jobs:
           echo "${{ secrets.DROPLET_SSH_KEY }}" > ~/.ssh/id_ed25519
           chmod 600 ~/.ssh/id_ed25519
           ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts
+      
+      - name: Debug SSH Key
+        run: |
+          ls -lah ~/.ssh/
+          cat ~/.ssh/id_ed25519 || echo "SSH key not found or cannot be read!"
+
 
       - name: Deploy via SSH to DigitalOcean Droplet
         if: success()  # Deploy only if tests pass
